---
# tasks file for ansible-role-yum-repos

- name: install plugins
  yum:
    name: "{{ item.name }}"
    state: present
    enablerepo: "{{ item.repo | default('') }}"
  with_items: "{{ yum_plugins }}"
  tags: [yum-repos]

- name: install CentOS-Base.repo only EC2
  copy: src=centos-base.repo dest=/etc/yum.repos.d/CentOS-Base.repo mode=0644 owner=root group=root force=no
  when: "ansible_distribution == 'Amazon'"
  tags: [yum-repos]

- name: install repository
  yum:
    name:  "{{ item.n }}"
    state: "{{ item.s | default('present') }}"
  with_items: "{{ yum_repositories }}"
  tags: [yum-repos]

- name: disable repository
  command: "yum-config-manager --{{ item.d | default('disable') }} {{ item.s }}"
  with_items: "{{ yum_disables }}"
  changed_when: false
  tags: [yum-repos]

